name: Java CI to create and upload release on push
on:
  push:
    branches: [ "master" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - run: ./gradlew build
      - run: mkdir staging && mv build/libs/omris-minestom-*.jar build/libs/omris-minestom-${{ env.build-number }}.jar && cp build/libs/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          path: staging/*.jar